# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 4 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

          # Options
          user: traeblain
          template: "@nord"
          setup_community_templates: traeblain/metrics@master:nord
          base: header
          config_timezone: America/Chicago
          # plugin_calendar: yes
          # plugin_calendar_limit: 0
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
